services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sns_service
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"