spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-44-215-22-37.compute-1.amazonaws.com/d7ek4uknp7ops6
  username: oluohgnicatyet
  password: f317a8626690f1cc373cc5c6e9720b6b84527530d614843e874866a107ad4e1b
  driver-class-name: org.postgresql.Driver

spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  show-sql: true
  open-in-view: false

jwt:
  secret:
    key: 612E3DFC176A8E32A3E59C2AC65D2612E3DFC176A8E32A3E59C2AC65D2
  token:
    expired-time: 2592000000
