server:
    http2:
      enabled: true
    tomcat:
      accept-count: 100
      max-connections: 8192

      threads:
        max: 200
        min-spare: 10


spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/sns_service?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/sns_service
    username: root
    password: 1234
  h2:
    console:
      enabled: true
  jpa:
#    show-sql: true
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    defer-datasource-initialization: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret:
    key: 612E3DFC176A8E32A3E59C2AC65D2612E3DFC176A8E32A3E59C2AC65D2
  token:
    expired-time: 86400000

